backend:
  name: github
  repo: GitRiviera/site_lubellule

# local_backend: true


media_folder: static/assets
public_folder: /assets
locale: 'en'
publish_mode: editorial_workflow

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "assets/galleries"
    create: true
    fields:
      - { label: "Folder Path", name: "folder_path", widget: "string" }
